filme/urls.py
# url - view - template
from django.urls import path, reverse_lazy
from .views import Homefilmes, Homepage, Detalhesfilme, PesquisaFilme, Paginaperfil, Criarconta
from django.contrib.auth import views as auth_view


app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),
    path('pesquisa/', PesquisaFilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('editarperfil/<int:pk>/', Paginaperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html', success_url=(reverse_lazy)), name='mudarsenha'),
]

openflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('filme.urls', namespace='filme')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
# Create your models here.

LISTA_CATEGORIAS = (
    ("ANIMACAO", "Animação"),
    ("AVENTURA", "Aventura"),
    ("OUTROS", "Outros"),
    ("AÇÃO", "Ação"),
    ("PODCAST", "Pdcast"),
    ("ROMANCE", "Romance")


)

# criar o filme
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=10000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.titulo


# criar os episodios
class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.filme.titulo + " - " + self.titulo

class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme")

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms

class FormHomePage(forms.Form):
    email = forms.EmailField(label=False)

class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

filme/views.py
from django.shortcuts import render, redirect, reverse
from .models import Filme, Usuario
from .forms import CriarContaForm, FormHomePage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
# def homepage(request):
#     return render(request, "homepage.html")

class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomePage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('filme:homefilmes')
        else:
            return super().get(request, *args, **kwargs) # redireciona para a a homepage

    def get_success_url(self):
        email = self.request.POST.get('email')
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse('filme:login')
        else:
            return reverse('filme:criarconta')



# Url - View - Html
# def homefilmes(request):
#     context = {}
#     lista_filmes = Filme.objects.all()
#     context['lista_filmes'] = lista_filmes
#     return render(request, "homefilmes.html", context)

class Homefilmes(LoginRequiredMixin, ListView):
    template_name = "homefilmes.html"
    model = Filme
    # object_list -> lista de itens do modelo




class Detalhesfilme(LoginRequiredMixin, DetailView):
    template_name = "detalhesfilme.html"
    model = Filme
    # object -> 1 item do nosso modelo

    def get(self, request, *args, **kwargs):
        filme = self.get_object()
        filme.visualizacoes += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs) # redireciona o usuario para a url final

    def get_context_data(self, **kwargs):
        context = super(Detalhesfilme, self).get_context_data(**kwargs)
        # filtrar a minha tabela de filmes pegando os filmes cuja categoria é igual a categoria do filme da página (object)
        # self.get_object()
        filmes_relacionados = Filme.objects.filter(categoria=self.get_object().categoria)[0:5]
        context["filmes_relacionados"] = filmes_relacionados
        return context


class PesquisaFilme(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Filme

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = self.model.objects.filter(titulo__icontains=termo_pesquisa)
            return object_list
        else:
            return None

class Paginaperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('filme:homefilmes')

class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('filme:login')

filme/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block titulo %}
Criar Conta
{% endblock %}

{% block content %}

    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/cinema3.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                   {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
            </form>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

        </ul>
    </footer>
{% endblock %}

filme/templates/detalhesfilme.html
{% extends 'base.html' %}
{% load static %}



{% block titulo %}
HomeFilmes Openflix
{% endblock %}


{% block head %}
<style>
html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

.flex-wrap {
  display: grid;
  grid-template-columns: repeat(3, 100%);
  overflow: hidden;
}

section {
  width: 100%;
  position: relative;
  display: grid;
  grid-template-columns: repeat(5, auto);
  margin: 10px 0;

  .item {
    padding: 0 2px;
    transition: all 250ms; /* Usando valor fixo em vez de variável Sass */

    &:hover {
      margin: 0 40px;
      transform: scale(1.2);
    }
  }
}
</style>
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover bg-black bg-opacity-50 bg-blend-overlay showcase bg-no-repeat" style="background-image: url('{{ object.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{ object.titulo }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ object.descricao|slice:":100" }}...
            </p>
            <div class="flex my-4">
                <a href="{{ object.episodios.first.video }}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
            </h2>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-lg">
                    {{ object.descricao }}
                    <br>
                    Visualizações: {{ object.visualizacoes }}
                </p>
            </div>

            <div style='margin-top:2rem;margin-bottom:2rem;'>
                {% if object.episodios.count > 1 %}
                    <h2 class="text-gray-200 text-3xl font-medium">
                        Episódios
                    </h2>
                    {% for episodio in object.episodios.all %}
                        <h3 class='text-lg'>
                            <a href="{{ episodio.video }}">
                                <p class="text-red-600">Episódio {{ forloop.counter }}: {{ episodio.titulo }}</p>
                            </a>
                        </h3>
                    {% endfor %}
                {% else %}
                    <section class="flex flex-col md:flex-row items-center border-dark border-b-8"></section>
                {% endif %}
            </div>


        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for filme in filmes_relacionados %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

</main>

{% endblock %}

filme/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
{% load bootstrap_icons %}


Editar Perfil
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/cinema3.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">{{ user.username }}</h2>
            {% csrf_token %}
            <form method="post">
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                   {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 mt-3 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
            </form>
            <small><a href="{% url 'filme:mudarsenha' %}" class="text-warning text-1xl ">Quer mudar sua senha?</a></small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>
					<a class="info" href="https://github.com/HugoLeandro" target="_blank" >
						<i class="fa-brands fa-github "></i>
						<span class="conversation-title text-light flex ml-4 justify-between items-center ">
							{% bs_icon 'github'%}<span class="ml-2">HugoLeandro</span>
						</span>
					</a>
            </li>
        </ul>
    </footer>


{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
HomeFilmes Openflix
{% endblock %}

{% block head %}
<style>
    $itemGrow: 1.2;
    $duration: 250ms;

    html {
      scroll-behavior: smooth;
    }

    body {
      margin: 0;
      background-color: #000;
    }

    .wrapper {
      display: grid;
      grid-template-columns: repeat(3, 100%);
      overflow: hidden;
      scroll-behavior: smooth;
    }

    section {
      width: 100%;
      position: relative;
      display: grid;
      grid-template-columns: repeat(5, auto);
      margin: 10px 0;

  .item {
    padding: 0 2px;
    transition: all 250ms; /* Usando valor fixo em vez de variável Sass */

    &:hover {
      margin: 0 40px;
      transform: scale(1.2);
    }
  }
</style>
{% endblock %}
{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase bg-no-repeat" style="background-image: url('{{ filme_destaque.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ filme_destaque.titulo }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-light my-4">
                    {{ filme_destaque.descricao }}
                </p>
                <div class="flex my-4">
                    <a href="{% url 'filme:detalhesfilme' filme_destaque.pk %}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium " >
                                Assistir
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Novo
                </h2>
                <div class="wrapper">
                  <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2" class="arrow__btn text-6xl text-light">‹</a>
                      {% for filme in lista_filmes_recentes %}
                      {% if forloop.counter < 5 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl text-light">›</a>
                  </section>
                    {% if lista_filmes_recentes|length > 4 %}
                      <section id="section2" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1" class="arrow__btn text-6xl text-light">‹</a>
                          {% for filme in lista_filmes_recentes %}
                          {% if forloop.counter > 4 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                          {% endif %}
                          {% endfor %}
                        <a href="#section1" class="arrow__btn text-6xl text-light">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Em Alta
                </h2>
                <div class="wrapper">
                  <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2emalta" class="arrow__btn text-6xl text-light">‹</a>
                      {% for filme in lista_filmes_emalta %}
                      {% if forloop.counter < 5 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                        <a href="#section2emalta" class="arrow__btn text-6xl text-light">›</a>
                  </section>
                    {% if lista_filmes_emalta|length > 4 %}
                      <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1emalta" class="arrow__btn text-6xl text-light">‹</a>
                          {% for filme in lista_filmes_emalta %}
                          {% if forloop.counter > 4 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                          {% endif %}
                          {% endfor %}
                        <a href="#section1emalta" class="arrow__btn text-6xl text-light">›</a>
                      </section>
                    {% endif %}
                </div>

            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Continuar Assistindo
                </h2>
                <div class="wrapper">
                  <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2vistos" class="arrow__btn text-6xl  text-light">‹</a>
                      {% for filme in request.user.filmes_vistos.all %}
                      {% if forloop.counter < 5 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                        <a href="#section2vistos" class="arrow__btn text-6xl text-light">›</a>
                  </section>
                    {% if request.user.filmes_vistos.all|length > 4 %}
                      <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1vistos" class="arrow__btn text-6xl text-light">‹</a>
                          {% for filme in request.user.filmes_vistos.all %}
                          {% if forloop.counter > 4 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                          {% endif %}
                          {% endfor %}
                        <a href="#section1vistos" class="arrow__btn text-6xl text-light">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>
    </main>

{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap_icons %}

{% block head %}
<style>
    #id_email {
        width: 100%;
        color: #000000;
        padding: 5px 5px;
    }
    #nav {
        padding: 5px
    }
</style>
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
{% endblock %}

{% block titulo %}
HomePage OpenFlix
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-dark border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Os filmes e séries mais populares, todos reunidos em um único lugar.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Assista onde preferir. Totalmente de graça.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Quer começar? Coloque seu e-mail abaixo para acessar.
            </h4>
            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        {% csrf_token %}
                        <div class="flex flex-grow items-stretch ">
                            {{ form }}
                        <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            <span>
                                Acessar
                            </span>
                            <ion-icon name="arrow-dropright" class=" text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-dark border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Divirta-se na sua TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Assista em Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players e muito mais.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-dark border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Baixe seus filmes para assistir offline.
            </h2>
            <h5 class="md:text-xl text-lg">
                Salve seus favoritos facilmente e tenha sempre algo para assistir.
            </h5>
        </div>

    </section>

    <section class='flex flex-col md:flex-row items-center border-dark border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Crie perfis para crianças.
            </h2>
            <h5 class="md:text-xl text-lg">
                Envie as crianças em aventuras com seus personagens favoritos em um espaço feito apenas para eles - grátis com sua assinatura.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/openflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2024</li>
            <li> Feito com Python (Django)</li>
            <li>
					<a class="info" href="https://github.com/HugoLeandro" target="_blank" >
						<i class="fa-brands fa-github "></i>
						<span class="conversation-title text-light flex ml-4 justify-between items-center ">
                            {% bs_icon 'github'%}<span class="ml-2">HugoLeandro</span>
						</span>
					</a>
            </li>
        </ul>
    </footer>


{% endblock %}

filme/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap_icons %}

{% block titulo %}
Fazer Login
{% endblock %}


{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-dark border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/cinema3.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Faça Login para continuar</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer Login</button>
            </form>
            <small>
                Não tem uma conta ainda?
                <p>
                    <a class="text-warning" href="{% url 'filme:criarconta' %}">Clique aqui para criar uma conta</a>
                </p>
            </small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>
					<a class="info" href="https://github.com/HugoLeandro" target="_blank" >
						<i class="fa-brands fa-github "></i>
						<span class="conversation-title text-light flex ml-4 justify-between items-center ">
							{% bs_icon 'github'%}<span class="ml-2">HugoLeandro</span>
						</span>
					</a>
            </li>
        </ul>
    </footer>
{% endblock %}

filme/templates/pesquisa.html
{% extends 'base.html' %}

{% block titulo %}
Pesquisa de Filmes
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Resultados da Busca
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                  {% for filme in object_list %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                          <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                  {% endfor %}
                </div>


            </div>
        </section>
    </main>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="w-full flex justify-between items-center py-3 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img class="2/12 pl-3"  src="{% static 'images/openflix_logo.png' %}">
        </a>
    </div>

    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
        <div class="mr-2">
            <form method="get" action="{% url 'filme:pesquisafilme'%}">
                <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar...">
                <input type="submit" value="">
            </form>
        </div>
        {% endif %}
        <div class="mr-2">
            {% if user.is_authenticated %}
            <a href="{% url 'filme:logout'%}">
                <button class="bg-red-600 text-white py-1 px-4 rounded-md">
                    Sair
                </button>
            </a>
            {% else %}
            <a href="{% url 'filme:login'%}">
                <button class="bg-red-600 text-white py-1 px-4 rounded-md">
                    Login
                </button>
            </a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="mr-2">
            <a href="{% url 'filme:editarperfil' pk=user.pk %}">
                <button class="bg-red-600 text-white py-1 px-4 rounded-md">
                    Editar Perfil
                </button>
            </a>
        </div>
        {% endif %}
    </div>

</nav>